iam -i does not create YAML config

diff --git a/include/init_instance b/include/init_instance
--- a/include/init_instance
+++ b/include/init_instance
@@ -39,6 +39,7 @@ if [[ "${INIT_INSTANCE_CREATE}" == "true" ]]; then
         else
             die "Failed to create instance '${INIT_INSTANCE}'"
         fi
+	[[ "${INIT_CONFIG_FORMAT}" == "yaml" ]] && /opt/airlock-iam/bin/iam config convert -i "${INIT_INSTANCE}" || die "Failed to convert instance '${INIT_INSTANCE}' to YAML config format"
     fi
 fi
 
